name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 1 * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: V1ck3s
          template: classic
          config_display: columns
          base: header, repositories
          commits_authoring: V1ck3s
          config_timezone: Europe/France
          config_output: svg
          config_width: 1000
          config_height: 350
          plugin_achievements: no
          plugin_achievements_display: detailed
          plugin_achievements_secrets: no
          plugin_achievements_threshold: C
          plugin_activity: no
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_habits: no
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_trim: yes
          plugin_introduction: no
          plugin_introduction_title: no
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 16
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: no
          plugin_people: no
          plugin_people_limit: 64
          plugin_people_shuffle: no
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_reactions: no
          plugin_reactions_display: absolute
          plugin_reactions_ignored: github-actions[bot], dependabot[bot], dependabot-preview[bot]
          plugin_reactions_limit: 200
          plugin_reactions_limit_issues: 100
          plugin_skyline: no
          plugin_skyline_frames: 60
          plugin_skyline_quality: 0.5
          plugin_skyline_year: current-year
          plugin_stargazers: no
          plugin_stars: no
          plugin_stars_limit: 4
          plugin_topics: no
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          plugin_traffic: no
          repositories_forks: no
